name: Pull Request

on:
  pull_request:
    branches:
      - candidate
    paths:
      - "snap/**"
      - ".github/**"
      - "test/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test Snap (amd64)
    runs-on: ubuntu-latest
    steps:
      - name: 🧪 Build snap
        run: |
          sudo snap install snapcraft --classic
        #
        #uses: snapcrafters/ci/test-snap-build@main

      - name: Setup LXD
        uses: canonical/setup-lxd@d14f946da89caa319fd083d39b1960f4978fb982

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Test snap
        run: |
          whoami
          lxc list
          lxd version
          lxc version
          snap info lxd
          #sudo usermod -aG lxd $USER
          #newgrp lxd
          snapcraft test --verbosity trace
