name: Pull Request

on:
  pull_request:
    branches:
      - candidate
    paths:
      - "snap/**"
      - ".github/**"
      - "test/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test Snap (amd64)
    runs-on: ubuntu-latest
    steps:
      - name: 🧪 Build snap
        uses: snapcrafters/ci/test-snap-build@main

      - name: Test snap
        run: |
          sg lxd -c 'snapcraft test'
